def extract_pyright_errors(pyright_json: dict) -> list[dict]:
    '''This function extracts the relevant information about the Pyright errors from the raw JSON output generated by running Pyright on the codebase.
    It takes the raw Pyright JSON output as input and returns a list of dictionaries representing each error, including the file path, line number, character position,
    error message, severity level, and the specific Pyright rule that was violated (if available). This structured 
    list of errors can be used for further processing by the Pyright reviewer agent to generate review messages based on the identified issues.'''
    
    diagnostics = pyright_json.get("generalDiagnostics", [])

    errors = []

    for diag in diagnostics:
        errors.append({
            "file": diag.get("file"),
            "line": diag.get("range", {}).get("start", {}).get("line", 0) + 1,
            "character": diag.get("range", {}).get("start", {}).get("character", 0),
            "message": diag.get("message"),
            "severity": diag.get("severity"),
            "rule": diag.get("rule", None)
        })

    return errors