from app.graph.state import GraphState  
import smtplib
from email.message import EmailMessage
from app.config.config import get_settings
from app.helper_functions.logger_functions import logger


def email_agent(state: GraphState):
    '''
    This agent compiles the consolidated reviews and code updates into a comprehensive email report and sends it to the user.
    It expects the state to have "consolidated_reviews", "consolidated_code_updates", and "pr_url" keys.
    The email is sent using SMTP to a local MailHog instance for testing purposes.
    '''
    
    msg = EmailMessage()
    settings = get_settings()

    pr_link = state.get("pr_url", "No PR link available")
    consolidated_reviews = state.get("consolidated_reviews", [])
    consolidated_updates = state.get("consolidated_code_updates", [])

    # ---- Build Errors Section ----
    errors_section = ""
    for review in consolidated_reviews:
        file_name = review.get("file", "Unknown File")
        errors_section += f"\n📄 File: {file_name}\n"

        for issue in review.get("issues", []):
            errors_section += (
                f"  - 🔴 [{issue.get('severity', 'UNKNOWN')}]\n"
                f"    Issue: {issue.get('issue')}\n"
                f"    Line: {issue.get('line')} | Char: {issue.get('character')}\n"
                f"    Source: {issue.get('source')}\n"
                f"    Recommended Fix: {issue.get('recommended_fix')}\n\n"
            )

    if not errors_section:
        errors_section = "No errors detected 🎉\n"

    # ---- Build Fixed Code Section ----
    fixes_section = ""
    for update in consolidated_updates:
        file_name = update.get("file", "Unknown File")
        updated_code = update.get("updated_code", "")

        fixes_section += (
            f"\n📄 File: {file_name}\n"
            f"-----------------------------\n"
            f"{updated_code}\n"
            f"-----------------------------\n"
        )

    if not fixes_section:
        fixes_section = "No code updates were required.\n"

    # ---- Email Metadata ----
    msg["Subject"] = "🚀 AI Code Review & Auto-Fix Report"
    msg["From"] = "agent@local.dev"
    msg["To"] = "test@example.com"

    msg.set_content(
        f"""
Your AI Agent has completed the code review and auto-fix process.

==============================
🛑 CONSOLIDATED ERRORS
==============================
{errors_section}

==============================
✅ CONSOLIDATED FIXES
==============================
{fixes_section}

==============================
🔗 PULL REQUEST
==============================
{pr_link}

---
Generated by AI Code Validator Agent 🤖
"""
    )
    
    logger.info("[EMAIL] Preparing review summary email")
    logger.info(f"[EMAIL] Sending to: {msg['To']}")

    with smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT) as server:
        server.send_message(msg)

    logger.info("[EMAIL] Email sent successfully")